#!/usr/bin/env bash

if [ "$USER" != "www-data" ]; then
    echo "must run this as www-data"
    exit 42
fi

cd /var/www/v9n.us
git pull
find . -type f -exec chmod a+r {} +
find . -type d -exec chmod a+rx {} +
